// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCustomAgent(arg1) {
  return window['go']['services']['AgentService']['AddCustomAgent'](arg1);
}

export function DisableProjectAgent(arg1, arg2, arg3) {
  return window['go']['services']['AgentService']['DisableProjectAgent'](arg1, arg2, arg3);
}

export function EnableProjectAgent(arg1, arg2) {
  return window['go']['services']['AgentService']['EnableProjectAgent'](arg1, arg2);
}

export function GetProjectAgentSkillCount(arg1, arg2) {
  return window['go']['services']['AgentService']['GetProjectAgentSkillCount'](arg1, arg2);
}

export function GetProjectAgents(arg1) {
  return window['go']['services']['AgentService']['GetProjectAgents'](arg1);
}

export function GetSupportedAgents() {
  return window['go']['services']['AgentService']['GetSupportedAgents']();
}

export function RemoveCustomAgent(arg1) {
  return window['go']['services']['AgentService']['RemoveCustomAgent'](arg1);
}

export function Startup(arg1) {
  return window['go']['services']['AgentService']['Startup'](arg1);
}
