// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateBackup(arg1, arg2, arg3) {
  return window['go']['services']['BackupService']['CreateBackup'](arg1, arg2, arg3);
}

export function DeleteBackup(arg1) {
  return window['go']['services']['BackupService']['DeleteBackup'](arg1);
}

export function GetBackupConfig() {
  return window['go']['services']['BackupService']['GetBackupConfig']();
}

export function GetBackupItems() {
  return window['go']['services']['BackupService']['GetBackupItems']();
}

export function GetBackups() {
  return window['go']['services']['BackupService']['GetBackups']();
}

export function RestoreBackup(arg1) {
  return window['go']['services']['BackupService']['RestoreBackup'](arg1);
}

export function SetBackupConfig(arg1) {
  return window['go']['services']['BackupService']['SetBackupConfig'](arg1);
}

export function Startup(arg1) {
  return window['go']['services']['BackupService']['Startup'](arg1);
}
