// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {context} from '../models';

export function CreateBackup(arg1:string,arg2:string,arg3:Array<string>):Promise<services.BackupInfo>;

export function DeleteBackup(arg1:string):Promise<void>;

export function GetBackupConfig():Promise<services.BackupConfig>;

export function GetBackupItems():Promise<Array<services.BackupItem>>;

export function GetBackups():Promise<Array<services.BackupInfo>>;

export function RestoreBackup(arg1:services.RestoreOptions):Promise<void>;

export function SetBackupConfig(arg1:services.BackupConfig):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
