// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {context} from '../models';

export function AnalyzeDependencies():Promise<services.DependencyAnalysis>;

export function AutoInstallDependencies(arg1:string,arg2:Array<string>):Promise<void>;

export function CreateInstallPlan(arg1:string):Promise<services.InstallPlan>;

export function GetDependencyGraph():Promise<services.DependencyGraph>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateDependencyInfo(arg1:string,arg2:services.SkillDependency):Promise<void>;
