// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeDependencies() {
  return window['go']['services']['DependencyService']['AnalyzeDependencies']();
}

export function AutoInstallDependencies(arg1, arg2) {
  return window['go']['services']['DependencyService']['AutoInstallDependencies'](arg1, arg2);
}

export function CreateInstallPlan(arg1) {
  return window['go']['services']['DependencyService']['CreateInstallPlan'](arg1);
}

export function GetDependencyGraph() {
  return window['go']['services']['DependencyService']['GetDependencyGraph']();
}

export function Startup(arg1) {
  return window['go']['services']['DependencyService']['Startup'](arg1);
}

export function UpdateDependencyInfo(arg1, arg2) {
  return window['go']['services']['DependencyService']['UpdateDependencyInfo'](arg1, arg2);
}
