// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckEnv() {
  return window['go']['services']['EnvService']['CheckEnv']();
}

export function InstallFindSkillsPlus() {
  return window['go']['services']['EnvService']['InstallFindSkillsPlus']();
}

export function InstallSkillsCLI() {
  return window['go']['services']['EnvService']['InstallSkillsCLI']();
}

export function RefreshEnv() {
  return window['go']['services']['EnvService']['RefreshEnv']();
}

export function Startup(arg1) {
  return window['go']['services']['EnvService']['Startup'](arg1);
}
