// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {context} from '../models';

export function CheckEnv():Promise<services.EnvStatus>;

export function InstallFindSkillsPlus():Promise<void>;

export function InstallSkillsCLI():Promise<void>;

export function RefreshEnv():Promise<services.EnvStatus>;

export function Startup(arg1:context.Context):Promise<void>;
