// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFolders() {
  return window['go']['services']['FolderService']['GetFolders']();
}

export function RemoveFolder(arg1) {
  return window['go']['services']['FolderService']['RemoveFolder'](arg1);
}

export function SelectFolder() {
  return window['go']['services']['FolderService']['SelectFolder']();
}

export function Startup(arg1) {
  return window['go']['services']['FolderService']['Startup'](arg1);
}
