// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearMetrics() {
  return window['go']['services']['MonitoringService']['ClearMetrics']();
}

export function ExportMetrics() {
  return window['go']['services']['MonitoringService']['ExportMetrics']();
}

export function GetAgentMetrics() {
  return window['go']['services']['MonitoringService']['GetAgentMetrics']();
}

export function GetPerformanceMetrics() {
  return window['go']['services']['MonitoringService']['GetPerformanceMetrics']();
}

export function GetSkillMetric(arg1) {
  return window['go']['services']['MonitoringService']['GetSkillMetric'](arg1);
}

export function GetSystemMetrics() {
  return window['go']['services']['MonitoringService']['GetSystemMetrics']();
}

export function GetUsageReport(arg1, arg2, arg3) {
  return window['go']['services']['MonitoringService']['GetUsageReport'](arg1, arg2, arg3);
}

export function ImportMetrics(arg1) {
  return window['go']['services']['MonitoringService']['ImportMetrics'](arg1);
}

export function RecordSkillUsage(arg1) {
  return window['go']['services']['MonitoringService']['RecordSkillUsage'](arg1);
}

export function Startup(arg1) {
  return window['go']['services']['MonitoringService']['Startup'](arg1);
}
