// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {time} from '../models';
import {context} from '../models';

export function ClearMetrics():Promise<void>;

export function ExportMetrics():Promise<Array<number>>;

export function GetAgentMetrics():Promise<Array<services.AgentMetric>>;

export function GetPerformanceMetrics():Promise<Array<services.PerformanceMetric>>;

export function GetSkillMetric(arg1:string):Promise<services.PerformanceMetric>;

export function GetSystemMetrics():Promise<services.SystemMetric>;

export function GetUsageReport(arg1:string,arg2:time.Time,arg3:time.Time):Promise<services.UsageReport>;

export function ImportMetrics(arg1:Array<number>):Promise<void>;

export function RecordSkillUsage(arg1:services.ExecutionContext):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
