// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyProfile(arg1) {
  return window['go']['services']['ProfileService']['ApplyProfile'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['services']['ProfileService']['DeleteProfile'](arg1);
}

export function GetProfiles() {
  return window['go']['services']['ProfileService']['GetProfiles']();
}

export function SaveCurrentAsProfile(arg1, arg2) {
  return window['go']['services']['ProfileService']['SaveCurrentAsProfile'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['services']['ProfileService']['Startup'](arg1);
}

export function UpdateProfile(arg1) {
  return window['go']['services']['ProfileService']['UpdateProfile'](arg1);
}
