// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {context} from '../models';

export function ApplyProfile(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function GetProfiles():Promise<services.ProfilesConfig>;

export function SaveCurrentAsProfile(arg1:string,arg2:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateProfile(arg1:string):Promise<void>;
