// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProvider(arg1) {
  return window['go']['services']['ProviderService']['AddProvider'](arg1);
}

export function DeactivateProvider(arg1) {
  return window['go']['services']['ProviderService']['DeactivateProvider'](arg1);
}

export function DeleteProvider(arg1) {
  return window['go']['services']['ProviderService']['DeleteProvider'](arg1);
}

export function DetectActiveProviders() {
  return window['go']['services']['ProviderService']['DetectActiveProviders']();
}

export function ExportProviders() {
  return window['go']['services']['ProviderService']['ExportProviders']();
}

export function GetAllProviders() {
  return window['go']['services']['ProviderService']['GetAllProviders']();
}

export function GetAvailableTerminals() {
  return window['go']['services']['ProviderService']['GetAvailableTerminals']();
}

export function GetCodeBuddyActiveModel() {
  return window['go']['services']['ProviderService']['GetCodeBuddyActiveModel']();
}

export function ImportProviders(arg1) {
  return window['go']['services']['ProviderService']['ImportProviders'](arg1);
}

export function OpenTerminalWithCLI(arg1) {
  return window['go']['services']['ProviderService']['OpenTerminalWithCLI'](arg1);
}

export function Startup(arg1) {
  return window['go']['services']['ProviderService']['Startup'](arg1);
}

export function SwitchCodeBuddyBuiltinModel(arg1) {
  return window['go']['services']['ProviderService']['SwitchCodeBuddyBuiltinModel'](arg1);
}

export function SwitchProvider(arg1) {
  return window['go']['services']['ProviderService']['SwitchProvider'](arg1);
}

export function TestProvider(arg1) {
  return window['go']['services']['ProviderService']['TestProvider'](arg1);
}

export function UpdateProvider(arg1) {
  return window['go']['services']['ProviderService']['UpdateProvider'](arg1);
}
