// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {context} from '../models';

export function AddProvider(arg1:string):Promise<services.ProviderConfig>;

export function DeactivateProvider(arg1:string):Promise<void>;

export function DeleteProvider(arg1:string):Promise<void>;

export function DetectActiveProviders():Promise<Record<string, string>>;

export function ExportProviders():Promise<string>;

export function GetAllProviders():Promise<services.ProvidersData>;

export function GetAvailableTerminals():Promise<Array<services.TerminalInfo>>;

export function GetCodeBuddyActiveModel():Promise<string>;

export function ImportProviders(arg1:string):Promise<number>;

export function OpenTerminalWithCLI(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function SwitchCodeBuddyBuiltinModel(arg1:string):Promise<void>;

export function SwitchProvider(arg1:string):Promise<void>;

export function TestProvider(arg1:string):Promise<services.ProviderTestResult>;

export function UpdateProvider(arg1:string):Promise<void>;
