// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {context} from '../models';

export function GetAllRatings():Promise<Record<string, services.SkillRating>>;

export function GetRating(arg1:string):Promise<services.SkillRating>;

export function SetRating(arg1:string,arg2:number,arg3:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
