// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllRatings() {
  return window['go']['services']['RatingService']['GetAllRatings']();
}

export function GetRating(arg1) {
  return window['go']['services']['RatingService']['GetRating'](arg1);
}

export function SetRating(arg1, arg2, arg3) {
  return window['go']['services']['RatingService']['SetRating'](arg1, arg2, arg3);
}

export function Startup(arg1) {
  return window['go']['services']['RatingService']['Startup'](arg1);
}
