// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DetectProjectType(arg1) {
  return window['go']['services']['RecommendationService']['DetectProjectType'](arg1);
}

export function GetRecommendations(arg1, arg2) {
  return window['go']['services']['RecommendationService']['GetRecommendations'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['services']['RecommendationService']['Startup'](arg1);
}
