// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {context} from '../models';

export function DetectProjectType(arg1:string):Promise<services.ProjectTypeDetection>;

export function GetRecommendations(arg1:string,arg2:number):Promise<Array<services.EnhancedRecommendation>>;

export function Startup(arg1:context.Context):Promise<void>;
