// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {context} from '../models';

export function ClearSearchHistory():Promise<void>;

export function GetSearchHistory(arg1:number):Promise<Array<services.SearchHistory>>;

export function GetSearchSuggestions(arg1:string,arg2:number):Promise<Array<services.SearchSuggestion>>;

export function RebuildIndex():Promise<void>;

export function Search(arg1:services.SearchQuery):Promise<services.SearchResult>;

export function Startup(arg1:context.Context):Promise<void>;
