// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearSearchHistory() {
  return window['go']['services']['SearchService']['ClearSearchHistory']();
}

export function GetSearchHistory(arg1) {
  return window['go']['services']['SearchService']['GetSearchHistory'](arg1);
}

export function GetSearchSuggestions(arg1, arg2) {
  return window['go']['services']['SearchService']['GetSearchSuggestions'](arg1, arg2);
}

export function RebuildIndex() {
  return window['go']['services']['SearchService']['RebuildIndex']();
}

export function Search(arg1) {
  return window['go']['services']['SearchService']['Search'](arg1);
}

export function Startup(arg1) {
  return window['go']['services']['SearchService']['Startup'](arg1);
}
