// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddActivityLog(arg1, arg2, arg3) {
  return window['go']['services']['SkillsService']['AddActivityLog'](arg1, arg2, arg3);
}

export function AddCustomSource(arg1, arg2, arg3) {
  return window['go']['services']['SkillsService']['AddCustomSource'](arg1, arg2, arg3);
}

export function BatchDeleteSkills(arg1) {
  return window['go']['services']['SkillsService']['BatchDeleteSkills'](arg1);
}

export function BatchUpdateSkillAgentLinks(arg1, arg2) {
  return window['go']['services']['SkillsService']['BatchUpdateSkillAgentLinks'](arg1, arg2);
}

export function CheckSkillUpdates() {
  return window['go']['services']['SkillsService']['CheckSkillUpdates']();
}

export function ClearActivityLogs() {
  return window['go']['services']['SkillsService']['ClearActivityLogs']();
}

export function CloneProjectConfig(arg1, arg2) {
  return window['go']['services']['SkillsService']['CloneProjectConfig'](arg1, arg2);
}

export function CreateCollection(arg1, arg2, arg3) {
  return window['go']['services']['SkillsService']['CreateCollection'](arg1, arg2, arg3);
}

export function CreateSkill(arg1, arg2, arg3, arg4) {
  return window['go']['services']['SkillsService']['CreateSkill'](arg1, arg2, arg3, arg4);
}

export function DeleteCollection(arg1) {
  return window['go']['services']['SkillsService']['DeleteCollection'](arg1);
}

export function DeleteSkill(arg1) {
  return window['go']['services']['SkillsService']['DeleteSkill'](arg1);
}

export function DetectProjectType(arg1) {
  return window['go']['services']['SkillsService']['DetectProjectType'](arg1);
}

export function ExportConfig() {
  return window['go']['services']['SkillsService']['ExportConfig']();
}

export function ExportConfigToFile() {
  return window['go']['services']['SkillsService']['ExportConfigToFile']();
}

export function FindRemoteSkills(arg1) {
  return window['go']['services']['SkillsService']['FindRemoteSkills'](arg1);
}

export function GetActivityLogs(arg1) {
  return window['go']['services']['SkillsService']['GetActivityLogs'](arg1);
}

export function GetAllAgentSkills() {
  return window['go']['services']['SkillsService']['GetAllAgentSkills']();
}

export function GetAllSkillTagsMap() {
  return window['go']['services']['SkillsService']['GetAllSkillTagsMap']();
}

export function GetAllTags() {
  return window['go']['services']['SkillsService']['GetAllTags']();
}

export function GetAutoUpdateConfig() {
  return window['go']['services']['SkillsService']['GetAutoUpdateConfig']();
}

export function GetAvailableEditors() {
  return window['go']['services']['SkillsService']['GetAvailableEditors']();
}

export function GetCollections() {
  return window['go']['services']['SkillsService']['GetCollections']();
}

export function GetCustomSources() {
  return window['go']['services']['SkillsService']['GetCustomSources']();
}

export function GetDashboardStats() {
  return window['go']['services']['SkillsService']['GetDashboardStats']();
}

export function GetFavorites() {
  return window['go']['services']['SkillsService']['GetFavorites']();
}

export function GetProjectSkillAgentLinks(arg1, arg2) {
  return window['go']['services']['SkillsService']['GetProjectSkillAgentLinks'](arg1, arg2);
}

export function GetProjectSkills(arg1) {
  return window['go']['services']['SkillsService']['GetProjectSkills'](arg1);
}

export function GetRecommendations() {
  return window['go']['services']['SkillsService']['GetRecommendations']();
}

export function GetSettings() {
  return window['go']['services']['SkillsService']['GetSettings']();
}

export function GetSkillAgentLinks(arg1) {
  return window['go']['services']['SkillsService']['GetSkillAgentLinks'](arg1);
}

export function GetSkillDetail(arg1) {
  return window['go']['services']['SkillsService']['GetSkillDetail'](arg1);
}

export function GetSkillDiff(arg1) {
  return window['go']['services']['SkillsService']['GetSkillDiff'](arg1);
}

export function GetSkillFiles(arg1) {
  return window['go']['services']['SkillsService']['GetSkillFiles'](arg1);
}

export function GetSkillTags(arg1) {
  return window['go']['services']['SkillsService']['GetSkillTags'](arg1);
}

export function GetSkillTemplates() {
  return window['go']['services']['SkillsService']['GetSkillTemplates']();
}

export function HealthCheck() {
  return window['go']['services']['SkillsService']['HealthCheck']();
}

export function ImportConfig(arg1) {
  return window['go']['services']['SkillsService']['ImportConfig'](arg1);
}

export function InstallCollection(arg1, arg2) {
  return window['go']['services']['SkillsService']['InstallCollection'](arg1, arg2);
}

export function InstallRemoteSkill(arg1, arg2) {
  return window['go']['services']['SkillsService']['InstallRemoteSkill'](arg1, arg2);
}

export function InstallRemoteSkillToProject(arg1, arg2, arg3) {
  return window['go']['services']['SkillsService']['InstallRemoteSkillToProject'](arg1, arg2, arg3);
}

export function InstallSkillToProject(arg1, arg2, arg3) {
  return window['go']['services']['SkillsService']['InstallSkillToProject'](arg1, arg2, arg3);
}

export function OpenSkillInEditor(arg1, arg2) {
  return window['go']['services']['SkillsService']['OpenSkillInEditor'](arg1, arg2);
}

export function OpenSkillInSystemEditor(arg1) {
  return window['go']['services']['SkillsService']['OpenSkillInSystemEditor'](arg1);
}

export function PreviewRemoteSkill(arg1) {
  return window['go']['services']['SkillsService']['PreviewRemoteSkill'](arg1);
}

export function RemoveCustomSource(arg1) {
  return window['go']['services']['SkillsService']['RemoveCustomSource'](arg1);
}

export function RemoveSkillFromProject(arg1, arg2) {
  return window['go']['services']['SkillsService']['RemoveSkillFromProject'](arg1, arg2);
}

export function RepairBrokenLinks() {
  return window['go']['services']['SkillsService']['RepairBrokenLinks']();
}

export function RunAutoUpdate() {
  return window['go']['services']['SkillsService']['RunAutoUpdate']();
}

export function SaveSettings(arg1) {
  return window['go']['services']['SkillsService']['SaveSettings'](arg1);
}

export function SaveSkillContent(arg1, arg2) {
  return window['go']['services']['SkillsService']['SaveSkillContent'](arg1, arg2);
}

export function SearchCustomSource(arg1) {
  return window['go']['services']['SkillsService']['SearchCustomSource'](arg1);
}

export function SetAutoUpdateConfig(arg1, arg2) {
  return window['go']['services']['SkillsService']['SetAutoUpdateConfig'](arg1, arg2);
}

export function SetSkillTags(arg1, arg2) {
  return window['go']['services']['SkillsService']['SetSkillTags'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['services']['SkillsService']['Startup'](arg1);
}

export function ToggleFavorite(arg1) {
  return window['go']['services']['SkillsService']['ToggleFavorite'](arg1);
}

export function UpdateCollection(arg1, arg2, arg3) {
  return window['go']['services']['SkillsService']['UpdateCollection'](arg1, arg2, arg3);
}

export function UpdateProjectSkillAgentLinks(arg1, arg2, arg3) {
  return window['go']['services']['SkillsService']['UpdateProjectSkillAgentLinks'](arg1, arg2, arg3);
}

export function UpdateSkill(arg1) {
  return window['go']['services']['SkillsService']['UpdateSkill'](arg1);
}

export function UpdateSkillAgentLinks(arg1, arg2) {
  return window['go']['services']['SkillsService']['UpdateSkillAgentLinks'](arg1, arg2);
}
