// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCustomAgent(arg1) {
  return window['go']['services']['SkillsService']['AddCustomAgent'](arg1);
}

export function DeleteSkill(arg1) {
  return window['go']['services']['SkillsService']['DeleteSkill'](arg1);
}

export function FindRemoteSkills(arg1) {
  return window['go']['services']['SkillsService']['FindRemoteSkills'](arg1);
}

export function GetAllAgentSkills() {
  return window['go']['services']['SkillsService']['GetAllAgentSkills']();
}

export function GetProjectSkillAgentLinks(arg1, arg2) {
  return window['go']['services']['SkillsService']['GetProjectSkillAgentLinks'](arg1, arg2);
}

export function GetProjectSkills(arg1) {
  return window['go']['services']['SkillsService']['GetProjectSkills'](arg1);
}

export function GetSkillAgentLinks(arg1) {
  return window['go']['services']['SkillsService']['GetSkillAgentLinks'](arg1);
}

export function GetSupportedAgents() {
  return window['go']['services']['SkillsService']['GetSupportedAgents']();
}

export function InstallRemoteSkill(arg1, arg2) {
  return window['go']['services']['SkillsService']['InstallRemoteSkill'](arg1, arg2);
}

export function InstallRemoteSkillToProject(arg1, arg2, arg3) {
  return window['go']['services']['SkillsService']['InstallRemoteSkillToProject'](arg1, arg2, arg3);
}

export function InstallSkillToProject(arg1, arg2, arg3) {
  return window['go']['services']['SkillsService']['InstallSkillToProject'](arg1, arg2, arg3);
}

export function RemoveCustomAgent(arg1) {
  return window['go']['services']['SkillsService']['RemoveCustomAgent'](arg1);
}

export function RemoveSkillFromProject(arg1, arg2) {
  return window['go']['services']['SkillsService']['RemoveSkillFromProject'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['services']['SkillsService']['Startup'](arg1);
}

export function UpdateProjectSkillAgentLinks(arg1, arg2, arg3) {
  return window['go']['services']['SkillsService']['UpdateProjectSkillAgentLinks'](arg1, arg2, arg3);
}

export function UpdateSkill(arg1) {
  return window['go']['services']['SkillsService']['UpdateSkill'](arg1);
}

export function UpdateSkillAgentLinks(arg1, arg2) {
  return window['go']['services']['SkillsService']['UpdateSkillAgentLinks'](arg1, arg2);
}
