// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {context} from '../models';

export function AddCustomAgent(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteSkill(arg1:string):Promise<void>;

export function FindRemoteSkills(arg1:string):Promise<Array<services.RemoteSkill>>;

export function GetAllAgentSkills():Promise<Array<services.Skills>>;

export function GetProjectSkillAgentLinks(arg1:string,arg2:string):Promise<Array<string>>;

export function GetProjectSkills(arg1:string):Promise<Array<services.ProjectSkill>>;

export function GetSkillAgentLinks(arg1:string):Promise<Array<string>>;

export function GetSupportedAgents():Promise<Array<services.AgentInfo>>;

export function InstallRemoteSkill(arg1:string,arg2:Array<string>):Promise<void>;

export function InstallRemoteSkillToProject(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function InstallSkillToProject(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function RemoveCustomAgent(arg1:string):Promise<void>;

export function RemoveSkillFromProject(arg1:string,arg2:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateProjectSkillAgentLinks(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function UpdateSkill(arg1:string):Promise<void>;

export function UpdateSkillAgentLinks(arg1:string,arg2:Array<string>):Promise<void>;
