// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCustomTemplate(arg1) {
  return window['go']['services']['TemplateService']['CreateCustomTemplate'](arg1);
}

export function GetEnhancedTemplates() {
  return window['go']['services']['TemplateService']['GetEnhancedTemplates']();
}

export function GetTemplateCategories() {
  return window['go']['services']['TemplateService']['GetTemplateCategories']();
}

export function RateTemplate(arg1, arg2, arg3) {
  return window['go']['services']['TemplateService']['RateTemplate'](arg1, arg2, arg3);
}

export function SearchTemplates(arg1, arg2, arg3) {
  return window['go']['services']['TemplateService']['SearchTemplates'](arg1, arg2, arg3);
}

export function Startup(arg1) {
  return window['go']['services']['TemplateService']['Startup'](arg1);
}
