// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {context} from '../models';

export function CreateCustomTemplate(arg1:services.EnhancedSkillTemplate):Promise<void>;

export function GetEnhancedTemplates():Promise<Array<services.EnhancedSkillTemplate>>;

export function GetTemplateCategories():Promise<Array<services.TemplateCategory>>;

export function RateTemplate(arg1:string,arg2:number,arg3:string):Promise<void>;

export function SearchTemplates(arg1:string,arg2:string,arg3:string):Promise<Array<services.EnhancedSkillTemplate>>;

export function Startup(arg1:context.Context):Promise<void>;
