// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RefreshTray() {
  return window['go']['services']['TrayService']['RefreshTray']();
}

export function Startup(arg1) {
  return window['go']['services']['TrayService']['Startup'](arg1);
}
