// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFolders():Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function RemoveFolder(arg1:string):Promise<void>;

export function SelectFolder():Promise<string>;
